package component:tools;

/// An example world for the component to target.
world example {
    record output {
        tokens: string,
        ast: string,
        wasm: list<u8>,
    }

    export get-tokens: func(source: string) -> string;
    export get-ast: func(source: string) -> string;
    export compile: func(source: string) -> output;
}
