/* prettier-ignore-start */

/* eslint-disable unicorn/no-abusive-eslint-disable */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from "@tanstack/react-router"

// Import Routes

import { Route as rootRoute } from "./routes/__root"
import { Route as studentProblemsProblemIdRouteImport } from "./routes/(student)/problems/$problemId/route"
import { Route as teacherAdminSubmissionsSubmissionIdRouteImport } from "./routes/(teacher)/admin/submissions/$submissionId/route"
import { Route as teacherAdminProblemsProblemIdIndexImport } from "./routes/(teacher)/admin/problems/$problemId/index"

// Create Virtual Routes

const studentRouteLazyImport = createFileRoute("/(student)")()
const studentProblemsIndexLazyImport = createFileRoute("/(student)/problems/")()
const studentdashbordIndexLazyImport = createFileRoute(
  "/(student)/(dashbord)/",
)()
const teacherAdminSubmissionsIndexLazyImport = createFileRoute(
  "/(teacher)/admin/submissions/",
)()
const teacherAdminProblemsIndexLazyImport = createFileRoute(
  "/(teacher)/admin/problems/",
)()

// Create/Update Routes

const studentRouteLazyRoute = studentRouteLazyImport
  .update({
    id: "/(student)",
    path: "/",
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import("./routes/(student)/route.lazy").then((d) => d.Route))

const studentProblemsIndexLazyRoute = studentProblemsIndexLazyImport
  .update({
    id: "/problems/",
    path: "/problems/",
    getParentRoute: () => studentRouteLazyRoute,
  } as any)
  .lazy(() =>
    import("./routes/(student)/problems/index.lazy").then((d) => d.Route),
  )

const studentdashbordIndexLazyRoute = studentdashbordIndexLazyImport
  .update({
    id: "/(dashbord)/",
    path: "/",
    getParentRoute: () => studentRouteLazyRoute,
  } as any)
  .lazy(() =>
    import("./routes/(student)/(dashbord)/index.lazy").then((d) => d.Route),
  )

const studentProblemsProblemIdRouteRoute = studentProblemsProblemIdRouteImport
  .update({
    id: "/problems/$problemId",
    path: "/problems/$problemId",
    getParentRoute: () => studentRouteLazyRoute,
  } as any)
  .lazy(() =>
    import("./routes/(student)/problems/$problemId/route.lazy").then(
      (d) => d.Route,
    ),
  )

const teacherAdminSubmissionsIndexLazyRoute =
  teacherAdminSubmissionsIndexLazyImport
    .update({
      id: "/(teacher)/admin/submissions/",
      path: "/admin/submissions/",
      getParentRoute: () => rootRoute,
    } as any)
    .lazy(() =>
      import("./routes/(teacher)/admin/submissions/index.lazy").then(
        (d) => d.Route,
      ),
    )

const teacherAdminProblemsIndexLazyRoute = teacherAdminProblemsIndexLazyImport
  .update({
    id: "/(teacher)/admin/problems/",
    path: "/admin/problems/",
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() =>
    import("./routes/(teacher)/admin/problems/index.lazy").then((d) => d.Route),
  )

const teacherAdminSubmissionsSubmissionIdRouteRoute =
  teacherAdminSubmissionsSubmissionIdRouteImport
    .update({
      id: "/(teacher)/admin/submissions/$submissionId",
      path: "/admin/submissions/$submissionId",
      getParentRoute: () => rootRoute,
    } as any)
    .lazy(() =>
      import(
        "./routes/(teacher)/admin/submissions/$submissionId/route.lazy"
      ).then((d) => d.Route),
    )

const teacherAdminProblemsProblemIdIndexRoute =
  teacherAdminProblemsProblemIdIndexImport
    .update({
      id: "/(teacher)/admin/problems/$problemId/",
      path: "/admin/problems/$problemId/",
      getParentRoute: () => rootRoute,
    } as any)
    .lazy(() =>
      import("./routes/(teacher)/admin/problems/$problemId/index.lazy").then(
        (d) => d.Route,
      ),
    )

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/(student)": {
      id: "/(student)"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof studentRouteLazyImport
      parentRoute: typeof rootRoute
    }
    "/(student)/problems/$problemId": {
      id: "/(student)/problems/$problemId"
      path: "/problems/$problemId"
      fullPath: "/problems/$problemId"
      preLoaderRoute: typeof studentProblemsProblemIdRouteImport
      parentRoute: typeof studentRouteLazyImport
    }
    "/(student)/(dashbord)/": {
      id: "/(student)/(dashbord)/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof studentdashbordIndexLazyImport
      parentRoute: typeof studentRouteLazyImport
    }
    "/(student)/problems/": {
      id: "/(student)/problems/"
      path: "/problems"
      fullPath: "/problems"
      preLoaderRoute: typeof studentProblemsIndexLazyImport
      parentRoute: typeof studentRouteLazyImport
    }
    "/(teacher)/admin/submissions/$submissionId": {
      id: "/(teacher)/admin/submissions/$submissionId"
      path: "/admin/submissions/$submissionId"
      fullPath: "/admin/submissions/$submissionId"
      preLoaderRoute: typeof teacherAdminSubmissionsSubmissionIdRouteImport
      parentRoute: typeof rootRoute
    }
    "/(teacher)/admin/problems/": {
      id: "/(teacher)/admin/problems/"
      path: "/admin/problems"
      fullPath: "/admin/problems"
      preLoaderRoute: typeof teacherAdminProblemsIndexLazyImport
      parentRoute: typeof rootRoute
    }
    "/(teacher)/admin/submissions/": {
      id: "/(teacher)/admin/submissions/"
      path: "/admin/submissions"
      fullPath: "/admin/submissions"
      preLoaderRoute: typeof teacherAdminSubmissionsIndexLazyImport
      parentRoute: typeof rootRoute
    }
    "/(teacher)/admin/problems/$problemId/": {
      id: "/(teacher)/admin/problems/$problemId/"
      path: "/admin/problems/$problemId"
      fullPath: "/admin/problems/$problemId"
      preLoaderRoute: typeof teacherAdminProblemsProblemIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface studentRouteLazyRouteChildren {
  studentProblemsProblemIdRouteRoute: typeof studentProblemsProblemIdRouteRoute
  studentdashbordIndexLazyRoute: typeof studentdashbordIndexLazyRoute
  studentProblemsIndexLazyRoute: typeof studentProblemsIndexLazyRoute
}

const studentRouteLazyRouteChildren: studentRouteLazyRouteChildren = {
  studentProblemsProblemIdRouteRoute: studentProblemsProblemIdRouteRoute,
  studentdashbordIndexLazyRoute: studentdashbordIndexLazyRoute,
  studentProblemsIndexLazyRoute: studentProblemsIndexLazyRoute,
}

const studentRouteLazyRouteWithChildren =
  studentRouteLazyRoute._addFileChildren(studentRouteLazyRouteChildren)

export interface FileRoutesByFullPath {
  "/": typeof studentdashbordIndexLazyRoute
  "/problems/$problemId": typeof studentProblemsProblemIdRouteRoute
  "/problems": typeof studentProblemsIndexLazyRoute
  "/admin/submissions/$submissionId": typeof teacherAdminSubmissionsSubmissionIdRouteRoute
  "/admin/problems": typeof teacherAdminProblemsIndexLazyRoute
  "/admin/submissions": typeof teacherAdminSubmissionsIndexLazyRoute
  "/admin/problems/$problemId": typeof teacherAdminProblemsProblemIdIndexRoute
}

export interface FileRoutesByTo {
  "/problems/$problemId": typeof studentProblemsProblemIdRouteRoute
  "/": typeof studentdashbordIndexLazyRoute
  "/problems": typeof studentProblemsIndexLazyRoute
  "/admin/submissions/$submissionId": typeof teacherAdminSubmissionsSubmissionIdRouteRoute
  "/admin/problems": typeof teacherAdminProblemsIndexLazyRoute
  "/admin/submissions": typeof teacherAdminSubmissionsIndexLazyRoute
  "/admin/problems/$problemId": typeof teacherAdminProblemsProblemIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  "/(student)": typeof studentRouteLazyRouteWithChildren
  "/(student)/problems/$problemId": typeof studentProblemsProblemIdRouteRoute
  "/(student)/(dashbord)/": typeof studentdashbordIndexLazyRoute
  "/(student)/problems/": typeof studentProblemsIndexLazyRoute
  "/(teacher)/admin/submissions/$submissionId": typeof teacherAdminSubmissionsSubmissionIdRouteRoute
  "/(teacher)/admin/problems/": typeof teacherAdminProblemsIndexLazyRoute
  "/(teacher)/admin/submissions/": typeof teacherAdminSubmissionsIndexLazyRoute
  "/(teacher)/admin/problems/$problemId/": typeof teacherAdminProblemsProblemIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/problems/$problemId"
    | "/problems"
    | "/admin/submissions/$submissionId"
    | "/admin/problems"
    | "/admin/submissions"
    | "/admin/problems/$problemId"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/problems/$problemId"
    | "/"
    | "/problems"
    | "/admin/submissions/$submissionId"
    | "/admin/problems"
    | "/admin/submissions"
    | "/admin/problems/$problemId"
  id:
    | "__root__"
    | "/(student)"
    | "/(student)/problems/$problemId"
    | "/(student)/(dashbord)/"
    | "/(student)/problems/"
    | "/(teacher)/admin/submissions/$submissionId"
    | "/(teacher)/admin/problems/"
    | "/(teacher)/admin/submissions/"
    | "/(teacher)/admin/problems/$problemId/"
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  studentRouteLazyRoute: typeof studentRouteLazyRouteWithChildren
  teacherAdminSubmissionsSubmissionIdRouteRoute: typeof teacherAdminSubmissionsSubmissionIdRouteRoute
  teacherAdminProblemsIndexLazyRoute: typeof teacherAdminProblemsIndexLazyRoute
  teacherAdminSubmissionsIndexLazyRoute: typeof teacherAdminSubmissionsIndexLazyRoute
  teacherAdminProblemsProblemIdIndexRoute: typeof teacherAdminProblemsProblemIdIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  studentRouteLazyRoute: studentRouteLazyRouteWithChildren,
  teacherAdminSubmissionsSubmissionIdRouteRoute:
    teacherAdminSubmissionsSubmissionIdRouteRoute,
  teacherAdminProblemsIndexLazyRoute: teacherAdminProblemsIndexLazyRoute,
  teacherAdminSubmissionsIndexLazyRoute: teacherAdminSubmissionsIndexLazyRoute,
  teacherAdminProblemsProblemIdIndexRoute:
    teacherAdminProblemsProblemIdIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/(student)",
        "/(teacher)/admin/submissions/$submissionId",
        "/(teacher)/admin/problems/",
        "/(teacher)/admin/submissions/",
        "/(teacher)/admin/problems/$problemId/"
      ]
    },
    "/(student)": {
      "filePath": "(student)/route.lazy.tsx",
      "children": [
        "/(student)/problems/$problemId",
        "/(student)/(dashbord)/",
        "/(student)/problems/"
      ]
    },
    "/(student)/problems/$problemId": {
      "filePath": "(student)/problems/$problemId/route.tsx",
      "parent": "/(student)"
    },
    "/(student)/(dashbord)/": {
      "filePath": "(student)/(dashbord)/index.lazy.tsx",
      "parent": "/(student)"
    },
    "/(student)/problems/": {
      "filePath": "(student)/problems/index.lazy.tsx",
      "parent": "/(student)"
    },
    "/(teacher)/admin/submissions/$submissionId": {
      "filePath": "(teacher)/admin/submissions/$submissionId/route.tsx"
    },
    "/(teacher)/admin/problems/": {
      "filePath": "(teacher)/admin/problems/index.lazy.tsx"
    },
    "/(teacher)/admin/submissions/": {
      "filePath": "(teacher)/admin/submissions/index.lazy.tsx"
    },
    "/(teacher)/admin/problems/$problemId/": {
      "filePath": "(teacher)/admin/problems/$problemId/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
