/* prettier-ignore-start */

/* eslint-disable unicorn/no-abusive-eslint-disable */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from "@tanstack/react-router"

// Import Routes

import { Route as rootRoute } from "./routes/__root"
import { Route as SubmissionsSubmissionIdRouteImport } from "./routes/submissions/$submissionId/route"
import { Route as ProblemsProblemIdRouteImport } from "./routes/problems/$problemId/route"

// Create Virtual Routes

const IndexLazyImport = createFileRoute("/")()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/index.lazy").then((d) => d.Route))

const SubmissionsSubmissionIdRouteRoute =
  SubmissionsSubmissionIdRouteImport.update({
    path: "/submissions/$submissionId",
    getParentRoute: () => rootRoute,
  } as any)

const ProblemsProblemIdRouteRoute = ProblemsProblemIdRouteImport.update({
  id: "/problems/$problemId",
  path: "/problems/$problemId",
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import("./routes/problems/$problemId/route.lazy").then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    "/problems/$problemId": {
      id: "/problems/$problemId"
      path: "/problems/$problemId"
      fullPath: "/problems/$problemId"
      preLoaderRoute: typeof ProblemsProblemIdRouteImport
      parentRoute: typeof rootRoute
    }
    "/submissions/$submissionId": {
      id: "/submissions/$submissionId"
      path: "/submissions/$submissionId"
      fullPath: "/submissions/$submissionId"
      preLoaderRoute: typeof SubmissionsSubmissionIdRouteImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexLazyRoute
  "/problems/$problemId": typeof ProblemsProblemIdRouteRoute
  "/submissions/$submissionId": typeof SubmissionsSubmissionIdRouteRoute
}

export interface FileRoutesByTo {
  "/": typeof IndexLazyRoute
  "/problems/$problemId": typeof ProblemsProblemIdRouteRoute
  "/submissions/$submissionId": typeof SubmissionsSubmissionIdRouteRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  "/": typeof IndexLazyRoute
  "/problems/$problemId": typeof ProblemsProblemIdRouteRoute
  "/submissions/$submissionId": typeof SubmissionsSubmissionIdRouteRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/problems/$problemId" | "/submissions/$submissionId"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/problems/$problemId" | "/submissions/$submissionId"
  id: "__root__" | "/" | "/problems/$problemId" | "/submissions/$submissionId"
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  ProblemsProblemIdRouteRoute: typeof ProblemsProblemIdRouteRoute
  SubmissionsSubmissionIdRouteRoute: typeof SubmissionsSubmissionIdRouteRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  ProblemsProblemIdRouteRoute: ProblemsProblemIdRouteRoute,
  SubmissionsSubmissionIdRouteRoute: SubmissionsSubmissionIdRouteRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/problems/$problemId",
        "/submissions/$submissionId"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/problems/$problemId": {
      "filePath": "problems/$problemId/route.tsx"
    },
    "/submissions/$submissionId": {
      "filePath": "submissions/$submissionId/route.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
